// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs3IzC_DhygDDGIR_Mc46rbJXzrGNtkdE',
    appId: '1:897134427610:web:b1f9fec78df84c20cf54e3',
    messagingSenderId: '897134427610',
    projectId: 'todoproject-8bfb6',
    authDomain: 'todoproject-8bfb6.firebaseapp.com',
    storageBucket: 'todoproject-8bfb6.appspot.com',
    measurementId: 'G-NQ775H08Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_St1bgIRCNvZQYjnM9IMk1LV_DsN3kc',
    appId: '1:897134427610:android:4e359c7da674dccfcf54e3',
    messagingSenderId: '897134427610',
    projectId: 'todoproject-8bfb6',
    storageBucket: 'todoproject-8bfb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQH6TPF52q37mY_cdPA9PsVXHANcEUE-8',
    appId: '1:897134427610:ios:d60220730cc790b4cf54e3',
    messagingSenderId: '897134427610',
    projectId: 'todoproject-8bfb6',
    storageBucket: 'todoproject-8bfb6.appspot.com',
    iosClientId: '897134427610-emcth0kn0so5nnr5h9tlpn0m11574kco.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQH6TPF52q37mY_cdPA9PsVXHANcEUE-8',
    appId: '1:897134427610:ios:681fb2e5110a35d2cf54e3',
    messagingSenderId: '897134427610',
    projectId: 'todoproject-8bfb6',
    storageBucket: 'todoproject-8bfb6.appspot.com',
    iosClientId: '897134427610-87k624cgquqauf64e3bmbtif0v2d9b70.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoproject.RunnerTests',
  );
}
